services:
  - type: web
    name: kemet-ai
    runtime: python
    buildCommand: pip install -r requirements.txt
    preDeployCommand: flask --app app db upgrade
    startCommand: gunicorn -c gunicorn.conf.py -b 0.0.0.0:$PORT "wsgi:application"
    healthCheckPath: /api/health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.15
      - key: PAYMENT_MODE
        value: paymob
      - key: DATABASE_URL
        fromDatabase:
          name: kemet-ai-db
          property: connectionString

databases:
  - name: kemet-ai-db
    plan: 0.1c-256mb
    region: frankfurt
    postgresMajorVersion: "18"
    connectionPool: none
