"""Add status to demo leads

Revision ID: 0c2507618602
Revises: 7a3b56b915c9
Create Date: 2026-08-07 23:32:55.437452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c2507618602'
down_revision = '7a3b56b915c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demo_leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=30), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demo_leads', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
