"""Fix ticket assignment foreign key

Revision ID: 0ea274fc17a7
Revises: dbb35056daac
Create Date: 2026-08-06 14:35:11.926847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ea274fc17a7'
down_revision = 'dbb35056daac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.String(length=20), nullable=False, server_default='medium'))
        batch_op.add_column(sa.Column('assigned_to_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_tickets_assigned_to_users', 'users', ['assigned_to_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tickets_assigned_to_users', type_='foreignkey')
        batch_op.drop_column('assigned_to_id')
        batch_op.drop_column('priority')

    # ### end Alembic commands ###
