from __future__ import annotations


INDUSTRY_PACKS = {
    "business": {
        "name": "Business",
        "description": "General business operations and management.",
        "entities": [
            "customers",
            "leads",
            "tasks",
            "projects",
            "invoices",
            "payments",
            "documents",
        ],
        "actions": [
            "create_ticket",
            "lead_scoring",
            "sales_follow_up",
            "customer_retention",
            "revenue_opportunity",
            "send_notification",
        ],
        "workforce": [
            "AI Business Manager",
            "AI Sales Agent",
            "AI Customer Success Agent",
            "AI Operations Agent",
            "AI Business Analyst",
        ],
        "metrics": [
            "revenue",
            "conversion_rate",
            "customer_retention",
            "sales_pipeline",
            "operational_efficiency",
        ],
    },
    "ecommerce": {
        "name": "E-Commerce",
        "description": "AI-powered online store operations.",
        "entities": [
            "products",
            "orders",
            "customers",
            "inventory",
            "payments",
            "returns",
            "coupons",
            "reviews",
            "suppliers",
            "shipments",
        ],
        "actions": [
            "check_order",
            "order_tracking",
            "payment_issue",
            "refund_request",
            "customer_retention",
            "churn_detection",
            "sales_follow_up",
            "send_notification",
        ],
        "workforce": [
            "AI Store Manager",
            "AI E-Commerce Sales Agent",
            "AI Order Agent",
            "AI Customer Support Agent",
            "AI Inventory Analyst",
            "AI Retention Agent",
        ],
        "metrics": [
            "revenue",
            "orders",
            "average_order_value",
            "conversion_rate",
            "return_rate",
            "customer_lifetime_value",
        ],
    },
    "real_estate": {
        "name": "Real Estate",
        "description": "AI-powered real estate sales and operations.",
        "entities": [
            "properties",
            "leads",
            "buyers",
            "sellers",
            "agents",
            "viewings",
            "offers",
            "deals",
            "commissions",
            "documents",
        ],
        "actions": [
            "lead_scoring",
            "sales_follow_up",
            "ai_sales_qualification",
            "customer_retention",
            "revenue_opportunity",
            "send_notification",
        ],
        "workforce": [
            "AI Real Estate Sales Agent",
            "AI Lead Qualifier",
            "AI Property Matching Agent",
            "AI Follow-Up Agent",
            "AI Real Estate Marketing Agent",
            "AI Deal Analyst",
        ],
        "metrics": [
            "qualified_leads",
            "viewings",
            "offers",
            "closed_deals",
            "sales_pipeline",
            "commission_revenue",
        ],
    },
    "marketing": {
        "name": "Marketing",
        "description": "AI-powered marketing operations and growth.",
        "entities": [
            "campaigns",
            "audiences",
            "content",
            "channels",
            "ads",
            "leads",
            "conversions",
            "analytics",
        ],
        "actions": [
            "lead_scoring",
            "sales_follow_up",
            "ai_sales_qualification",
            "revenue_opportunity",
            "send_notification",
        ],
        "workforce": [
            "AI Marketing Manager",
            "AI Content Agent",
            "AI Ads Analyst",
            "AI SEO Agent",
            "AI Social Media Agent",
            "AI Campaign Optimizer",
            "AI Lead Generation Agent",
        ],
        "metrics": [
            "reach",
            "engagement",
            "cost_per_lead",
            "conversion_rate",
            "customer_acquisition_cost",
            "return_on_ad_spend",
        ],
    },
    "sales": {
        "name": "Sales",
        "description": "AI-powered sales pipeline and revenue operations.",
        "entities": [
            "leads",
            "contacts",
            "accounts",
            "opportunities",
            "deals",
            "activities",
            "quotations",
            "customers",
        ],
        "actions": [
            "lead_scoring",
            "sales_follow_up",
            "ai_sales_qualification",
            "customer_retention",
            "churn_detection",
            "revenue_opportunity",
            "send_notification",
        ],
        "workforce": [
            "AI Sales Manager",
            "AI SDR Agent",
            "AI Lead Qualification Agent",
            "AI Follow-Up Agent",
            "AI Account Manager",
            "AI Revenue Analyst",
        ],
        "metrics": [
            "leads",
            "qualified_leads",
            "opportunities",
            "win_rate",
            "sales_cycle",
            "pipeline_value",
            "revenue",
        ],
    },
}
